# Generated by Django 2.2.3 on 2019-07-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BobHandeling',
            fields=[
                ('dvom_bobhandelingid', models.AutoField(primary_key=True, serialize=False)),
                ('dvom_bobhandeling', models.CharField(max_length=100, verbose_name='BOB handeling')),
                ('dvom_aanvraagpv', models.CharField(max_length=50, verbose_name='Aanvraag PV')),
            ],
        ),
    ]
