# Generated by Django 2.2.3 on 2019-07-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0002_auto_20190710_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_heterdaad',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Heterdaad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_onderzoeksinstantiecontactpersoon',
            field=models.CharField(default=None, help_text='Contactpersoon bij de opsporingsdienst', max_length=100, verbose_name='Contactpersoon onderzoeksinstantie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_onderzoekstype',
            field=models.CharField(choices=[('SO', 'Strafrechtelijk Onderzoek'), ('SF', 'Strafrechtelijk Financieel Onderzoek'), ('SE', 'Strafrechtelijk Executie Onderzoek')], default=None, help_text='Type onderzoek (wordt afgeleid van de bevoegdheid)', max_length=2, verbose_name='Onderzoekstype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_verbalisantcontactgegevens',
            field=models.EmailField(help_text='Contactgegevens van de verbalisant', max_length=254, verbose_name='Verbalisant'),
        ),
    ]
