# Generated by Django 2.2.3 on 2019-07-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0003_auto_20190710_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_heterdaad',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Heterdaad'),
        ),
    ]
