# Generated by Django 2.2.3 on 2019-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0004_auto_20190710_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_heterdaad',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nee')], default=False, verbose_name='Heterdaad'),
        ),
    ]
