# Generated by Django 2.2.3 on 2019-07-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0006_bobhandeling_dvom_heeftverlenging'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_verlenging',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nee')], default=False, verbose_name='Verlenging'),
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_verlengingeinddatum',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_verlengingingaandop',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_bobhandeling',
            field=models.CharField(help_text='Naam van de bob handeling', max_length=100, verbose_name='BOB handeling'),
        ),
    ]
