# Generated by Django 2.2.3 on 2019-07-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0007_auto_20190710_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_verlenging_aantal',
            field=models.IntegerField(default=0, help_text='Voor hoe lang wordt de verlenging van de handeling gevraagd (aantal i.c.m.volgend veld', verbose_name='Periode verlenging (aantal)'),
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_verlenging_periode',
            field=models.CharField(choices=[('DD', 'Dag/Dagen'), ('WW', 'Week/Weken'), ('MM', 'Maand/Maanden')], default=None, help_text='Eenheid van de periode waarvoor de verlenging van de handeling gevraagd wordt', max_length=2, verbose_name='Periode verlenging (eenheid)'),
            preserve_default=False,
        ),
    ]
