# Generated by Django 2.2.3 on 2019-07-10 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0009_auto_20190710_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_datumpv',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_verlenging_aantal',
            field=models.PositiveIntegerField(default=0, help_text='Voor hoe lang wordt de verlenging van de handeling gevraagd (aantal i.c.m.volgend veld)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Periode verlenging (aantal)'),
        ),
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_verlenging_periode',
            field=models.CharField(choices=[('DD', 'Dag/Dagen'), ('WW', 'Week/Weken'), ('MM', 'Maand/Maanden')], help_text='Eenheid van de periode waarvoor \n                                           de verlenging van de handeling gevraagd wordt', max_length=2, verbose_name='Periode verlenging (eenheid)'),
        ),
    ]
