# Generated by Django 2.2.3 on 2019-07-10 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0010_auto_20190710_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_verlenging_aantal',
            field=models.PositiveIntegerField(default=0, help_text='Voor hoe lang wordt de verlenging van de handeling gevraagd \n                                             (aantal i.c.m.volgend veld)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Periode verlenging (aantal)'),
        ),
    ]
