# Generated by Django 2.2.3 on 2019-07-10 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0011_auto_20190710_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_oorspronkelijkebobhandelingid',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_periode_aantal',
            field=models.PositiveIntegerField(default=0, help_text='Periode vordering tot machtiging  \n                                             (aantal i.c.m.volgend veld)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Aantal (periode)'),
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_periode_periode',
            field=models.CharField(choices=[('DD', 'Dag/Dagen'), ('WW', 'Week/Weken'), ('MM', 'Maand/Maanden')], default=None, help_text='Eenheid van de periode tot vordering tot machtiging  \n                                           ', max_length=2, verbose_name='Periode (eenheid)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_voorgaandebobhandelingid',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_vtmeinddatum',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_vtmstartdatum',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
