# Generated by Django 2.2.3 on 2019-07-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0012_auto_20190710_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_vtmstartdatum',
            field=models.DateField(verbose_name='VTMStartdatum / Op'),
        ),
    ]
