# Generated by Django 2.2.3 on 2019-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0013_auto_20190710_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_vtmeinddatum',
            field=models.DateField(verbose_name='VTMEinddatum'),
        ),
    ]
