# Generated by Django 2.2.3 on 2019-07-11 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0014_auto_20190710_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_machtiging_aantal',
            field=models.PositiveIntegerField(default=0, help_text='Periode van de machtiging  \n                                             (aantal i.c.m.volgend veld)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Machtiging aantal (periode)'),
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_machtiging_periode',
            field=models.CharField(choices=[('DD', 'Dag/Dagen'), ('WW', 'Week/Weken'), ('MM', 'Maand/Maanden')], default=None, help_text='Eenheid van de periode van de machtiging ', max_length=2, verbose_name='Machtiging periode (eenheid)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_machtigingdoorid',
            field=models.CharField(default=None, help_text='RC die de machtiging \n                                             afgeeft (id van de gebruiker in de applicatie)', max_length=10, verbose_name='Machtiging door'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_machtigingeinddatum',
            field=models.DateField(default=None, help_text='Einddatum\n                                                 van de machtiging', verbose_name='Machtiging einddatum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_machtigingop',
            field=models.DateField(default=None, help_text='Datum waarop de machtiging is \n                                        afgegeven', verbose_name='Machtiging op'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_machtigingstartdatum',
            field=models.DateField(default=None, help_text='Startdatum\n                                                 van de machtiging', verbose_name='Machtiging startdatum / op'),
            preserve_default=False,
        ),
    ]
