# Generated by Django 2.2.3 on 2019-07-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0015_auto_20190711_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_onderzoeksinstantieid',
            field=models.CharField(blank=True, help_text='ID van de opsporingsinstantie (NB: zit in Onderzoek)', max_length=100, null=True, verbose_name='Onderzoeksinstantie'),
        ),
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_onderzoekssubjectid',
            field=models.CharField(blank=True, help_text='ID van het onderzoekssubject ', max_length=100, null=True, verbose_name='Onderzoekssubject'),
        ),
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_onderzoeksinstantiecontactpersoon',
            field=models.CharField(help_text='Contactpersoon bij de opsporingsinstantie', max_length=100, verbose_name='Contactpersoon onderzoeksinstantie'),
        ),
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_oorspronkelijkebobhandelingid',
            field=models.CharField(help_text='ID van de 1e BOB handeling waar \n                                                          de verlenging bij hoort', max_length=100, verbose_name='Oorspronkelijke BOB handeling'),
        ),
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_voorgaandebobhandelingid',
            field=models.CharField(help_text='ID voorgaande BOB handeling (igv verlenging)', max_length=100, verbose_name='Voorgaande BOB handeling'),
        ),
    ]
