# Generated by Django 2.2.3 on 2019-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0016_auto_20190711_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobhandeling',
            name='dvom_strafvorderlijkebevoegdheidid',
            field=models.CharField(default='', help_text='ID van de \n                                                          bevoegdheid ', max_length=100, verbose_name='Bevoegdheid'),
        ),
    ]
