# Generated by Django 2.2.3 on 2019-07-15 19:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bob', '0018_auto_20190713_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_machtiging_aantal',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Periode van de machtiging  \n                                             (aantal i.c.m.volgend veld)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Machtiging aantal (periode)'),
        ),
        migrations.AlterField(
            model_name='bobhandeling',
            name='dvom_verlengingnr',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Hoeveelste verlenging betreft het', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Verlenging nr'),
        ),
        migrations.CreateModel(
            name='Onderzoek',
            fields=[
                ('dvom_onderzoekid', models.AutoField(primary_key=True, serialize=False)),
                ('dvom_locatieid', models.CharField(choices=[('NL', 'Nederland'), ('BE', 'Belgie')], default='', max_length=10, verbose_name='Parket')),
                ('dvom_naam', models.CharField(blank=True, max_length=100, null=True, verbose_name='Onderzoeksnaam')),
                ('dvom_codenaam', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codenaam')),
                ('dvom_onderzoeksinstantieid', models.CharField(max_length=10, verbose_name='Onderzozeksinstantie')),
                ('dvom_procesverbaalnummer', models.CharField(max_length=100, verbose_name='Process verbaal nummer')),
                ('dvom_classificatie', models.CharField(blank=True, choices=[('FR', 'Fraude'), ('JE', 'Jeugd'), ('MH', 'Mensenhandel'), ('MI', 'Militair'), ('TR', 'Terrorisme')], max_length=2, null=True, verbose_name='Classificatie')),
                ('dvom_naamcsv', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam CSV')),
                ('dvom_omschrijvingcsv', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Omschrijving CSV')),
                ('dvom_afsluitenonderzoek', models.CharField(blank=True, choices=[('1', 'Er is geen verdachte'), ('2', 'Klappen zaak - de verdacht wordt vervolgd'), ('3', 'Sepot')], max_length=1, null=True, verbose_name='Afsluiten onderzoek')),
                ('np_bobaanvraagid', models.IntegerField()),
                ('dvom_zaakgriffierid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zaakgriffier_onderzoeken', to=settings.AUTH_USER_MODEL, verbose_name='Zaaksgriffier')),
                ('dvom_zaakovjid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zaakovj_onderzoeken', to=settings.AUTH_USER_MODEL, verbose_name='ZaaksOvJ')),
                ('dvom_zaakparketsecrid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zaakparketsecr_onderzoeken', to=settings.AUTH_USER_MODEL, verbose_name='Zaakssecretaris')),
                ('dvom_zaakrcid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zaakrc_onderzoeken', to=settings.AUTH_USER_MODEL, verbose_name='ZaaksRC')),
            ],
            options={
                'verbose_name_plural': 'Onderzoeken',
                'ordering': ['-dvom_onderzoekid'],
            },
        ),
    ]
