# Generated by Django 2.2.3 on 2019-07-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0019_auto_20190715_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobhandeling',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='PDF document: '),
        ),
    ]
