# Generated by Django 2.2.3 on 2019-10-14 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NatuurlijkPersoonProcesVerbaal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(blank=True, max_length=30, null=True)),
                ('voorvoegsel', models.CharField(blank=True, max_length=10, null=True)),
                ('achternaam', models.CharField(max_length=30)),
                ('geslacht', models.CharField(blank=True, choices=[('man', 'Man'), ('vrouw', 'Vrouw')], max_length=5, null=True)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('geboorteland', models.CharField(blank=True, choices=[('NL', 'Nederland'), ('MA', 'Marokko'), ('TU', 'Turkije'), ('GE', 'Duitsland'), ('BE', 'Belgie'), ('PL', 'Polen')], max_length=2, null=True)),
                ('nationaliteit', models.CharField(blank=True, max_length=100, null=True)),
                ('adres', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('plaats', models.CharField(blank=True, max_length=100, null=True, verbose_name='Woonplaats')),
                ('land', models.CharField(blank=True, choices=[('NL', 'Nederland'), ('MA', 'Marokko'), ('TU', 'Turkije'), ('GE', 'Duitsland'), ('BE', 'Belgie'), ('PL', 'Polen')], max_length=2, null=True, verbose_name='Land')),
                ('keno_nummer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesVerbaal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_nummer', models.CharField(max_length=50, verbose_name='PV nummer')),
                ('bvh_nummer', models.CharField(blank=True, max_length=50, null=True, verbose_name='BVH nummer')),
                ('naam_ovj', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam Officier van Justitie')),
                ('parket_nummer', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_nummer', models.CharField(blank=True, max_length=100, null=True)),
                ('toelichting', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_document', models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='PDF bijlage')),
                ('entity_type', models.CharField(choices=[('np', 'Natuurlijk persoon'), ('rp', 'Rechtspersoon')], default='np', max_length=2, verbose_name='Onderzoek richt zich op')),
                ('jegens_persoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.NatuurlijkPersoonProcesVerbaal')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RechtsPersoonProcesVerbaal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(blank=True, max_length=40, null=True)),
                ('rechtsvorm', models.CharField(blank=True, max_length=40, null=True)),
                ('statutaire_adres', models.CharField(blank=True, max_length=100, null=True)),
                ('vestiging_adres', models.CharField(blank=True, max_length=100, null=True)),
                ('post_adres', models.CharField(blank=True, max_length=100, null=True)),
                ('kvk_nummer', models.CharField(blank=True, max_length=50, null=True)),
                ('vertegenwoordiger', models.CharField(max_length=50)),
                ('functie', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerbalisantProcesVerbaal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam')),
                ('email', models.EmailField(max_length=254)),
                ('rang', models.CharField(max_length=100, verbose_name='Rang')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesVerbaalAanvraag',
            fields=[
                ('procesverbaal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.ProcesVerbaal')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.procesverbaal',),
        ),
        migrations.CreateModel(
            name='ProcesVerbaalVerdenking',
            fields=[
                ('procesverbaal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.ProcesVerbaal')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.procesverbaal',),
        ),
        migrations.AddField(
            model_name='procesverbaal',
            name='jegens_rechtspersoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.RechtsPersoonProcesVerbaal'),
        ),
        migrations.AddField(
            model_name='procesverbaal',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_resources.procesverbaal_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='procesverbaal',
            name='verbalisanten',
            field=models.ManyToManyField(blank=True, to='resources.VerbalisantProcesVerbaal'),
        ),
        migrations.CreateModel(
            name='ProcesVerbaalHistorischeGegevens',
            fields=[
                ('procesverbaalaanvraag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.ProcesVerbaalAanvraag')),
                ('jegens_verdachte', models.CharField(choices=[('verdachte', 'Verdachte'), ('betrokkene', 'Betrokkene')], max_length=20, verbose_name='Jegens verdachte')),
                ('start_datum', models.DateField()),
                ('eind_datum', models.DateField()),
                ('rekeningnummer', models.CharField(max_length=30, verbose_name='IBAN nummer')),
                ('financiele_instelling', models.CharField(max_length=100, verbose_name='Financiele instelling')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.procesverbaalaanvraag',),
        ),
        migrations.CreateModel(
            name='BOBAanvraag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('naam_ovj', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam Officier van Justitie')),
                ('parket_nummer', models.CharField(blank=True, max_length=100, null=True)),
                ('naam_onderzoek', models.CharField(blank=True, max_length=200, null=True)),
                ('rc_nummer', models.CharField(blank=True, max_length=100, null=True)),
                ('mondeling_aanvraag_bevestiging', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nee')], default=False, help_text='Betreft het een bevestiging mondelinge aanvraag', verbose_name='Bevestiging mondelinge aanvraag?')),
                ('mondeling_aanvraag_datum', models.DateField(blank=True, null=True)),
                ('onderzoeksbelang_toelichting', models.TextField(blank=True, null=True, verbose_name='Toelichting op het onderzoeksbelang:')),
                ('verstrekking_gegevens_aan', models.CharField(blank=True, choices=[('verba', 'Verbalisant'), ('ander', 'Andere')], max_length=5, null=True, verbose_name='Aan wie gegevens verstrekken:')),
                ('verbalisant', models.CharField(help_text='Naam van de verbalisant', max_length=100, verbose_name='Naam verbalisant')),
                ('verbalisant_email', models.EmailField(help_text='Contactgegevens van de verbalisant', max_length=254, verbose_name='E-mail verbalisant')),
                ('bijlage_toevoegen', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nee')], default=False, verbose_name='Bijlagen')),
                ('bijlage', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Bijlage')),
                ('status', django_fsm.FSMField(default='aangemaakt', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bob_aanvragen', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bob_aanvragen', to=settings.AUTH_USER_MODEL)),
                ('pv_aanvraag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ProcesVerbaalAanvraag')),
                ('pv_verdenking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ProcesVerbaalVerdenking')),
            ],
        ),
    ]
