# Generated by Django 2.2.3 on 2019-09-23 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOBAanvraag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('naam_ovj', models.CharField(blank=True, max_length=100, null=True)),
                ('parket_nummer', models.CharField(blank=True, max_length=100, null=True)),
                ('naam_onderzoek', models.CharField(blank=True, max_length=200, null=True)),
                ('rc_nummer', models.CharField(blank=True, max_length=100, null=True)),
                ('mondeling_aanvraag_bevestiging', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nee')], default=False, help_text='Betreft het een bevestiging mondelinge aanvraag', verbose_name='Mondelinge aanvraag')),
                ('mondeling_aanvraag_datum', models.DateField(blank=True, null=True)),
                ('pv_nummer', models.CharField(max_length=50, verbose_name='PV nummer')),
                ('onderzoeksbelang_toelichting', models.TextField(blank=True, null=True, verbose_name='Toelichting op het onderzoeksbelang:')),
                ('verstrekking_gegevens_aan', models.CharField(blank=True, choices=[('verba', 'Verbalisant'), ('ander', 'Andere')], max_length=5, null=True, verbose_name='Aan wie gegevens verstrekken:')),
                ('verbalisant', models.CharField(help_text='Naam van de verbalisant', max_length=100, verbose_name='Naam verbalisant')),
                ('verbalisant_email', models.EmailField(help_text='Contactgegevens van de verbalisant', max_length=254, verbose_name='E-mail verbalisant')),
                ('bijlage_toevoegen', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nee')], default=False, verbose_name='Bijlagen')),
                ('bijlage', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Bijlage')),
                ('status', django_fsm.FSMField(default='aangemaakt', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bob_aanvragen', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bob_aanvragen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
