# Generated by Django 2.2.3 on 2019-08-12 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOBAanvraag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvom_aanvraagpv', models.CharField(max_length=50, verbose_name='Aanvraag PV')),
                ('dvom_datumpv', models.DateField()),
                ('dvom_verbalisant', models.CharField(help_text='Naam van de verbalisant', max_length=100, verbose_name='Naam verbalisant')),
                ('dvom_verbalisantcontactgegevens', models.EmailField(help_text='Contactgegevens van de verbalisant', max_length=254, verbose_name='E-mail verbalisant')),
                ('dvom_strafvorderlijkebevoegdheidid', models.CharField(default='', help_text='ID van de \n                                                          bevoegdheid ', max_length=100, verbose_name='Bevoegdheid')),
                ('dvom_verlenging', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nee')], default=False, verbose_name='Verlenging')),
                ('dvom_verlengingingaandop', models.DateField()),
                ('dvom_verlengingeinddatum', models.DateField()),
                ('dvom_verlenging_aantal', models.PositiveIntegerField(default=0, help_text='Voor hoe lang wordt de verlenging van de handeling gevraagd \n                                             (aantal i.c.m.volgend veld)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Periode verlenging (aantal)')),
                ('dvom_verlenging_periode', models.CharField(choices=[('DD', 'Dag/Dagen'), ('WW', 'Week/Weken'), ('MM', 'Maand/Maanden')], help_text='Eenheid van de periode waarvoor \n                                           de verlenging van de handeling gevraagd wordt', max_length=2, verbose_name='Periode verlenging (eenheid)')),
                ('dvom_vtmstartdatum', models.DateField(verbose_name='VTMStartdatum / Op')),
                ('dvom_vtmeinddatum', models.DateField(verbose_name='VTMEinddatum')),
                ('dvom_periode_aantal', models.PositiveIntegerField(default=0, help_text='Periode vordering tot machtiging  \n                                             (aantal i.c.m.volgend veld)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Aantal (periode)')),
                ('dvom_periode_periode', models.CharField(choices=[('DD', 'Dag/Dagen'), ('WW', 'Week/Weken'), ('MM', 'Maand/Maanden')], help_text='Eenheid van de periode tot vordering tot machtiging  \n                                           ', max_length=2, verbose_name='Periode (eenheid)')),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='PDF Document')),
            ],
        ),
    ]
