# Generated by Django 2.2.3 on 2019-08-19 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobaanvraag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobaanvraag',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bob_aanvragen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bobaanvraag',
            name='status',
            field=django_fsm.FSMField(default='aangemaakt', max_length=50),
        ),
        migrations.AddField(
            model_name='bobaanvraag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bobaanvraag',
            name='dvom_periode_aantal',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Periode vordering tot machtiging  \n                                                                      (aantal i.c.m.volgend veld)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Aantal (periode)'),
        ),
        migrations.AlterField(
            model_name='bobaanvraag',
            name='dvom_periode_periode',
            field=models.CharField(blank=True, choices=[('DD', 'Dag/Dagen'), ('WW', 'Week/Weken'), ('MM', 'Maand/Maanden')], help_text='Eenheid van de periode tot vordering tot machtiging', max_length=2, null=True, verbose_name='Periode (eenheid)'),
        ),
        migrations.AlterField(
            model_name='bobaanvraag',
            name='dvom_verlenging_aantal',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Voor hoe lang wordt de verlenging van de handeling gevraagd \n                                             (aantal i.c.m.volgend veld)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Periode verlenging (aantal)'),
        ),
        migrations.AlterField(
            model_name='bobaanvraag',
            name='dvom_verlenging_periode',
            field=models.CharField(blank=True, choices=[('DD', 'Dag/Dagen'), ('WW', 'Week/Weken'), ('MM', 'Maand/Maanden')], help_text='Eenheid van de periode waarvoor \n                                                            de verlenging van de handeling gevraagd wordt', max_length=2, null=True, verbose_name='Periode verlenging (eenheid)'),
        ),
        migrations.AlterField(
            model_name='bobaanvraag',
            name='dvom_verlengingeinddatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bobaanvraag',
            name='dvom_verlengingingaandop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bobaanvraag',
            name='dvom_vtmeinddatum',
            field=models.DateField(blank=True, null=True, verbose_name='VTMEinddatum'),
        ),
        migrations.AlterField(
            model_name='bobaanvraag',
            name='dvom_vtmstartdatum',
            field=models.DateField(blank=True, null=True, verbose_name='VTMStartdatum / Op'),
        ),
    ]
