# Generated by Django 2.2.3 on 2019-10-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesverbaal',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('np', 'Natuurlijk persoon'), ('rp', 'Rechtspersoon')], default='np', max_length=2, verbose_name='Onderzoek richt zich op'),
        ),
    ]
