# Generated by Django 2.2.3 on 2019-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobaanvraag',
            name='mondeling_aanvraag_bevestiging',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nee')], default=False, help_text='Betreft het een bevestiging mondelinge aanvraag', verbose_name='Bevestiging mondelinge aanvraag?'),
        ),
        migrations.AlterField(
            model_name='bobaanvraag',
            name='naam_ovj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam Officier van Justitie'),
        ),
    ]
