# Generated by Django 2.2.3 on 2019-09-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20190928_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100, verbose_name='Voornaam')),
                ('achternaam', models.CharField(max_length=100, verbose_name='Achternaam')),
                ('email', models.EmailField(max_length=254)),
                ('mobiel', models.CharField(max_length=20, verbose_name='Mobiel')),
            ],
        ),
        migrations.CreateModel(
            name='Verbalisant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('email', models.EmailField(max_length=254)),
                ('rang', models.CharField(max_length=100, verbose_name='Rang')),
            ],
        ),
        migrations.RemoveField(
            model_name='bobaanvraag',
            name='pv_nummer',
        ),
        migrations.CreateModel(
            name='NatuurlijkPersoon',
            fields=[
                ('persoon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Persoon')),
            ],
            bases=('resources.persoon',),
        ),
        migrations.CreateModel(
            name='RechtsPersoon',
            fields=[
                ('persoon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Persoon')),
            ],
            bases=('resources.persoon',),
        ),
        migrations.CreateModel(
            name='PvVerdenking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_nummer', models.CharField(max_length=50, verbose_name='PV nummer')),
                ('bvh_nummer', models.CharField(max_length=50, verbose_name='BVH nummer')),
                ('naam_ovj', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam Officier van Justitie')),
                ('parket_nummer', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_nummer', models.CharField(blank=True, max_length=100, null=True)),
                ('verbalisanten', models.ManyToManyField(blank=True, to='resources.Verbalisant')),
                ('natuurlijkpersoon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.NatuurlijkPersoon')),
                ('rechtspersoon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.RechtsPersoon')),
            ],
        ),
        migrations.AddField(
            model_name='bobaanvraag',
            name='pv_verdenking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.PvVerdenking'),
        ),
    ]
