# Generated by Django 2.2.3 on 2019-10-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20191014_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbalisantprocesverbaal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='verbalisantprocesverbaal',
            name='rang',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rang'),
        ),
    ]
