# Generated by Django 2.2.3 on 2019-10-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20190929_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvverdenking',
            name='verbalisanten',
            field=models.ManyToManyField(blank=True, null=True, to='resources.Verbalisant'),
        ),
    ]
