# Generated by Django 2.2.3 on 2019-10-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20191001_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvverdenking',
            name='natuurlijkpersoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.NatuurlijkPersoon'),
        ),
        migrations.AlterField(
            model_name='pvverdenking',
            name='rechtspersoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.RechtsPersoon'),
        ),
    ]
