# Generated by Django 2.2.3 on 2019-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20191001_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbalisant',
            name='naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam'),
        ),
    ]
